name: Check Python Files Only

on:
  push:
    branches:
      - main
      - develop

jobs:
  check_files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for non-Python files
        run: |
          if git show --name-only --pretty=format: ${{ github.sha }} | grep -qvE '\.py$'; then
            echo "Error: Non-Python files found in commit."
            exit 1
          else
            echo "All files are Python files."
          fi
