name: Check Python and YAML Files Only

on:
  push:
    branches:
      - main
      - develop

jobs:
  check_files:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Check for non-Python or non-YAML files
        run: |
          if git show --name-only --pretty=format: ${{ github.sha }} | awk -F/ '!/\.py$|\.yml$/ { exit 1 }'; then
            echo "All files are Python or YAML files."
          else
            echo "Error: Non-Python or Non-YAML files found in commit."
            exit 1
          fi
